# _config.yml

title: "Joshua Adams"
email: "joshadams@protonmail.com"
description: "Certified Business Continuity Professional (CBCP) | IT & Cybersecurity Specialist | Researcher | Educator"
baseurl: ""        # if publishing to USER.github.io, keep this blank
url: "https://yourusername.github.io"  # or your custom domain if set up

theme: minima

# any plugins you want to activate
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# files or folders to skip in your final build
exclude:
  - Gemfile.lock
  - node_modules